version: "3.8"

services:
  app:
    image: frontend-development
    build: .
    command: npm start
    environment:
      NODE_ENV: development
    ports: 
      - "3000:3000"
    working_dir: /opt/app
    volumes:
      - ./src:/opt/app/src
      - ./public:/opt/app/public
      - ./.gitignore:/opt/app/.gitignore
      - ./.eslintrc.json:/opt/app/.eslintrc.json
      - ./tsconfig.json:/opt/app/tsconfig.json
      - ./package.json:/opt/app/package.json
      - ./README.md:/opt/app/README.md
