name: Build

on:
  push:
    branches: [ github-workflows-test, backend-connect-test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: npm clean-install
    - name: Build
      run: npm run build