name: ESLint check

on:
  push:
    branches: [ github-workflows-test, backend-connect-test ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm clean-install
    - name: Run tests
      run: npm run lint-check